# Generated by Django 4.1.1 on 2022-10-04 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=12, unique=True, verbose_name='Cedula')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('celular', models.CharField(max_length=10, unique=True, verbose_name='Celular')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('contrasena', models.CharField(max_length=15, unique=True, verbose_name='Contrasena')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('tipo_de_identificacion', models.CharField(max_length=50, verbose_name='tipo de identificacion')),
                ('nro_identificacion', models.CharField(max_length=50, unique=True, verbose_name='Numero de identificacion')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('celular', models.CharField(max_length=50, unique=True, verbose_name='celular')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.empleados')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_sgnvital', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=20, verbose_name='Fecha')),
                ('oximetria', models.CharField(max_length=10, verbose_name='Oximetría')),
                ('frecuencia_respiratoria', models.CharField(max_length=10, verbose_name='Frecuencia respiratoria')),
                ('frecuencia_cardiaca', models.CharField(max_length=10, verbose_name='Frecuencia cardiaca')),
                ('temperatura', models.CharField(max_length=10, verbose_name='Temperatura')),
                ('presion_arterial', models.CharField(max_length=10, verbose_name='Presion Arterial')),
                ('glicemia', models.CharField(max_length=10, verbose_name='contrasena')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('id_hc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=100)),
                ('code_patologia', models.CharField(max_length=15)),
                ('tratamiento', models.CharField(max_length=50)),
                ('cuidados', models.CharField(max_length=50)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.empleados')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('celular', models.CharField(max_length=50, unique=True, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('genero', models.CharField(max_length=50, verbose_name='Genero')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.pacientes')),
            ],
        ),
    ]
